#setwd("d:/statistics/agricolae/R")
setwd("f:/statistics/agricolae/R")
library(agricolae)
data(CIC)
data(ComasOxapampa)
data(Glycoalkaloids)
data(LxT)
data(carolina1)
data(carolina2)
data(carolina3)
data(clay)
data(cotton)
data(disease)
data(friedman)
data(genxenv)
data(growth)
data(haynes)
data(homog1)
data(huasahuasi)
data(kruskal)
data(ltrv)
data(markers)
data(melon)
data(natives)
data(paracsho)
data(plots)
data(potato)
data(precipitation)
data(ralstonia)
data(rice)
data(sensorial)
data(sinRepAmmi)
data(soil)
data(stable)
data(sweetpotato)
data(trees)
data(wild)

source("	AMMI.R	")
source("	audpc.abs.R	")
source("	audpc.rel.R	")
source("	bar.err.R	")
source("	bar.group.R	")
source("	c.kurtosis.R	")
source("	c.skewness.R	")
source("	carolina.R	")
source("	coeff.diana.R	")
source("	cor.matrix.R	")
source("	cor.mv.R	")
source("	cor.vector.R	")
source("	correl.R	")
source("	cv.model.R	")
source("	cv.similarity.R	")
source("	decimals.R	")
source("	delete.na.R	")
source("	design.ab.R	")
source("	design.crd.R	")
source("	design.graeco.R	")
source("	design.lsd.R	")
source("	design.rcbd.R	")
source("	dimnames.order.R	")
source("	durbin.comp.R	")
source("	durbin.group.R	")
source("	fact.nk.R	")
source("	friedman.comp.R	")
source("	friedman.group.R	")
source("	graph.freq.R	")
source("	grid3d.R	")
source("	grid3p.R	")
source("	gxyz.R	")
source("	HSD.group.R	")
source("	HSD.R	")
source("	index.bio.R	")
source("	index.smith.R	")
source("	intervals.freq.R	")
source("	join.freq.R	")
source("	kendall.R	")
source("	kruskal.comp.R	")
source("	kruskal.group.R	")
source("	last.c.R	")
source("	lattice.simple.R	")
source("	lineXtester.R	")
source("	LSD.group.R	")
source("	LSD.R	")
source("	mxyz.R	")
source("	nonadditivity.R	")
source("	normal.freq.R	")
source("	ojiva.freq.R	")
source("	order.group.R	")
source("	order.stat.R	")
source("	path.analysis.R	")
source("	plot.disc.R	")
source("	polygon.freq.R	")
source("	random.ab.R	")
source("	reg.homog.R	")
source("	resampling.cv.R	")
source("	resampling.model.R	")
source("	similarity.R	")
source("	simulation.model.R	")
source("	stability.nonpar.R	")
source("	stability.par.R	")
source("	stat.freq.R	")
source("strip.plot.R")
source("	sturges.freq.R	")
source("	table.freq.R	")
source("	tapply.stat.R	")
source("	VanderWarden.r") 
source("	VanderWarden.group.r") 
source("	vark.R	")
source("	waller.comp.R	")
source("	waller.group.R	")
source("	waller.R	")
source("	wxyz.R	")

package.skeleton(name="agricolae",list=ls(), path="d:/", force=T)

